### ISSUE TITLE
hfst-ospell doesn't build on macosx <= 10.6 because of missing strndup

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst-ospell#4]
To repeat:

`````` ~
./configure
...
checking for GNU libc compatible malloc... yes
checking for strndup... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating hfstospell.pc
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
-- Building hfstospell 0.2.4
    * zhfst support: yes
    * extracting to: mem
    * xml support: yes
hfst-ospell$ make
make  all-am
  CXX      libhfstospell_la-hfst-ol.lo
  CXX      libhfstospell_la-ospell.lo
  CXX      libhfstospell_la-ZHfstOspeller.lo
  CXX      libhfstospell_la-ZHfstOspellerXmlMetadata.lo
ZHfstOspellerXmlMetadata.cc: In function ‘char* hfst_ol::get_automaton_descr_from_id(Glib::ustring)’:
ZHfstOspellerXmlMetadata.cc:251: error: ‘strndup’ was not declared in this scope
make[1]: *** [libhfstospell_la-ZHfstOspellerXmlMetadata.lo] Error 1
```~

This bug only relates to MacOSX 10.6 or older, but is nevertheless important, because hfst-ospell needs to build on MacOSX 10.4 to be able to fully support LibreOffice/OpenOffice for all versions of MacOSX they run on (support via libvoikko and the LO voikko plugin).

The bug is described several places, and an easy workaround exists. See e.g. [this][1] and [this][2], and implementation code is available [here][3].






Reported by: snomos
``````
